# Generated by Django 5.2.6 on 2026-10-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodada',
            name='data_inicio',
            field=models.DateTimeField(blank=True, help_text="Momento em que a rodada passou para 'Em Andamento'. Usado para saber quem estava inscrito na rodada (bye). Nulo em rodadas antigas.", null=True),
        ),
        migrations.AlterField(
            model_name='rodada',
            name='status',
            field=models.CharField(default='Pendente', help_text='Ex: Emparelhamento, Em Andamento, Finalizada', max_length=50),
        ),
    ]
