# Generated by Django 5.2.6 on 2026-10-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0003_corrige_nomes_e_textos_nulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='data_inscricao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='decklist',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('Inscrito', 'Inscrito'), ('Cancelado', 'Cancelado')], default='Inscrito', max_length=50),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='pontuacao_time_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='pontuacao_time_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='time_vencedor',
            field=models.IntegerField(blank=True, choices=[(0, 'Empate'), (1, 'Time 1'), (2, 'Time 2')], help_text='Nulo enquanto o resultado não foi reportado.', null=True),
        ),
        migrations.AlterField(
            model_name='mesajogador',
            name='time',
            field=models.IntegerField(choices=[(1, 'Time 1'), (2, 'Time 2')]),
        ),
        migrations.AlterField(
            model_name='rankingparcial',
            name='balanco',
            field=models.DecimalField(decimal_places=4, help_text='OMW% - PMW% (pode ser negativo).', max_digits=6),
        ),
        migrations.AlterField(
            model_name='rankingparcial',
            name='data_calculo',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rankingparcial',
            name='mw_percentage',
            field=models.DecimalField(decimal_places=4, help_text='Match Win % (piso de 1%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='rankingparcial',
            name='omw_percentage',
            field=models.DecimalField(decimal_places=4, help_text='Média do MW% dos oponentes.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='rankingparcial',
            name='pmw_percentage',
            field=models.DecimalField(decimal_places=4, help_text='Média do MW% dos parceiros.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='rankingparcial',
            name='pontos_totais',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rankingparcial',
            name='posicao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rankingparcial',
            name='rodada_numero',
            field=models.IntegerField(help_text='Até qual rodada foi calculado.'),
        ),
        migrations.AlterField(
            model_name='rodada',
            name='status',
            field=models.CharField(choices=[('Emparelhamento', 'Emparelhamento'), ('Em Andamento', 'Em Andamento'), ('Finalizada', 'Finalizada')], default='Emparelhamento', max_length=50),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='banner',
            field=models.CharField(blank=True, default='', help_text='Nome do arquivo do banner no frontend (ex: b1.png).', max_length=255),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='inscricao_gratuita',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='pontuacao_bye',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='pontuacao_derrota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='pontuacao_empate',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='pontuacao_vitoria',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='qnt_vagas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='quantidade_rodadas',
            field=models.PositiveIntegerField(blank=True, help_text='Limite de rodadas. Vazio = sem limite.', null=True),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='regras',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Em Andamento', 'Em Andamento'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Aberto', max_length=50),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='vagas_limitadas',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='valor_inscricao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor da inscrição em reais.', max_digits=10, null=True),
        ),
    ]
