# Generated by Django 5.2.6 on 2026-10-06 19:32

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_token_sem_nulo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', usuarios.models.GerenciadorUsuario()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='status',
            field=models.CharField(default='ativo', help_text='Ex: ativo, inativo, banido.', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('JOGADOR', 'Jogador'), ('LOJA', 'Loja'), ('ADMIN', 'Admin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='token_redefinir_senha',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='token_redefinir_senha_criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
