# Generated by Django 5.2.6 on 2026-10-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_redefinir_senha_criado_em',
            field=models.DateTimeField(blank=True, help_text='Momento em que o token de redefinição foi gerado (usado para expirar o token).', null=True),
        ),
    ]
